/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_guoguo_jni_JniDemo */

#ifndef _Included_com_guoguo_jni_JniDemo
#define _Included_com_guoguo_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_guoguo_jni_JniDemo
 * Method:    sayHello
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_guoguo_jni_JniDemo_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
